#!/usr/bin/env node
/* =========================================================================
   Measure the built home page and write src/data/metrics.json.

     npm run build && npm run measure && npm run build

   The home page states what it weighs. That number has to come from the
   real build output, or it is just another marketing claim — which is the
   thing this site is arguing against. So: build, measure, rebuild with the
   measured numbers baked in.

   The second build changes the byte count slightly (the digits themselves
   change width). That is why the page reports a rounded figure and the
   exact bytes live here, and why the copy invites you to check in DevTools.

   Node standard library only.
   ========================================================================= */
'use strict';

import { readFile, writeFile, stat } from 'node:fs/promises';
import { gzipSync } from 'node:zlib';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const DIST = path.join(ROOT, 'dist');
const OUT = path.join(ROOT, 'src', 'data', 'metrics.json');
const ENTRY = path.join(DIST, 'index.html');

/** Everything the home page pulls from this origin, in load order. */
async function collect() {
  const html = await readFile(ENTRY, 'utf8');
  const assets = new Set();

  // Stylesheets, scripts, preloaded fonts, images, and the favicon.
  const patterns = [
    /<link[^>]+rel=["']stylesheet["'][^>]+href=["']([^"']+)["']/gi,
    /<link[^>]+href=["']([^"']+)["'][^>]+rel=["']stylesheet["']/gi,
    /<link[^>]+rel=["'](?:preload|icon)["'][^>]+href=["']([^"']+)["']/gi,
    /<script[^>]+src=["']([^"']+)["']/gi,
    /<img[^>]+src=["']([^"']+)["']/gi,
  ];

  for (const re of patterns) {
    for (const [, href] of html.matchAll(re)) {
      if (href.startsWith('http') || href.startsWith('data:')) {
        throw new Error(
          `Third-party or inline-data request found on the home page: ${href}\n` +
            'Zero third-party requests is a hard constraint (REBUILD-BRIEF.md §5).'
        );
      }
      assets.add(href.split('?')[0]);
    }
  }

  // Fonts referenced from the bundled CSS that the page actually loads.
  for (const href of [...assets]) {
    if (!href.endsWith('.css')) continue;
    const css = await readFile(path.join(DIST, href.replace(/^\//, '')), 'utf8');
    for (const [, url] of css.matchAll(/url\(["']?([^"')]+\.woff2)["']?\)/gi)) {
      /* Only the subsets this page actually downloads. unicode-range means
         a subset is fetched only when a character in its range appears, and
         English and Portuguese both sit entirely inside the Latin subset —
         ã õ ç á é í ó ú are all under U+00FF. Counting latin-ext here would
         inflate the page by ~77 KB that no visitor ever receives. */
      if (!/-latin\.woff2$/i.test(url)) continue;
      assets.add(url.split('?')[0]);
    }
  }

  return [...assets];
}

const bytes = async (rel) => {
  const file = path.join(DIST, rel.replace(/^\//, ''));
  const info = await stat(file);
  const raw = await readFile(file);
  // woff2 and webp are already compressed; the server will not gzip them again.
  const compressible = /\.(html|css|js|svg|json|txt|xml)$/i.test(rel);
  return { raw: info.size, wire: compressible ? gzipSync(raw).length : info.size };
};

const kb = (n) => Math.round((n / 1024) * 10) / 10;

const assets = await collect();
const entry = await bytes('/index.html');

let wire = entry.wire;
let raw = entry.raw;
for (const rel of assets) {
  const size = await bytes(rel);
  wire += size.wire;
  raw += size.raw;
}

const metrics = {
  /* Regenerated by scripts/measure.mjs — do not hand-edit. */
  measuredAt: new Date().toISOString().slice(0, 10),
  page: '/',
  requests: assets.length + 1, // + the document itself
  thirdPartyRequests: 0,
  weightKb: kb(wire),
  weightRawKb: kb(raw),
  cookies: 0,
  assets: assets.sort(),
};

await writeFile(OUT, JSON.stringify(metrics, null, 2) + '\n');

console.log(`home page: ${metrics.requests} requests, ${metrics.weightKb} KB over the wire`);
console.log(`           ${metrics.weightRawKb} KB uncompressed, ${metrics.thirdPartyRequests} third-party`);
for (const a of metrics.assets) console.log(`           · ${a}`);
console.log(`\nwritten to src/data/metrics.json — rebuild to bake it in`);
